// Auto-generated schema paths for Cloudflare Workers compatibility
// Relative paths from ./src/ folder to schema modules

export const arrayOfSchemaPaths = [
    '../node_modules/schemaimporter/schemas/v1.2.0/alternative-me/fearAndGreed.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/coins.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/derivatives.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/exchanges.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/getCategories.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/global.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/simplePrice.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/coingecko-com/trending.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/cointelegraph/getLatestNews.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/context-7/getDocumentation.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/defilama/api.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/defilama/coins.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/defilama/yields.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/dexscreener-com/boosted.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/dexscreener-com/pairs.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/dexscreener-com/tokenInfo.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/erc725/profileJump.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/jupiter/jupiter-all.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/llama-fi/getPools.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/address.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/blocks.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/graphql.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/internal.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/nfts.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/search.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/sourceCode.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/stats.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/tokens.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/lukso-network/transactions.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/memory-lol/twitterNameChanges.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/poap/graphql.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/polymarket/marketInfo.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/polymarket/searchBySlug.mjs',
    '../node_modules/schemaimporter/schemas/v1.2.0/reddit/getTokenMentions.mjs'
]